### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by noohv** [noohv/employee-management#11]
Things I need to implement
- [x] Job Title delete
- [x]  Job Title update
- [x]  Schedule delete
- [x]  Schedule update
- [x] Absence edit
- [x]  Finish form validations
- [x]  Finish error messages from server side

**Comment by noohv** [comment]
Environment: **LOCAL**
**Tested OK**
